# Generated by Django 5.1.7 on 2025-04-11 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_navigations', to='store.product')),
                ('source_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_navigations', to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_navigations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='store_produ_created_8a0fd8_idx'), models.Index(fields=['user'], name='store_produ_user_id_41ca0b_idx'), models.Index(fields=['source_product'], name='store_produ_source__06d84e_idx'), models.Index(fields=['destination_product'], name='store_produ_destina_e63e14_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['viewed_at'], name='store_produ_viewed__c7f606_idx'), models.Index(fields=['product'], name='store_produ_product_bf080b_idx'), models.Index(fields=['user'], name='store_produ_user_id_56a54a_idx')],
            },
        ),
    ]
