# Generated by Django 5.1.7 on 2025-04-11 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productnavigation_productview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productnavigation',
            name='search_query',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='productnavigation',
            index=models.Index(fields=['search_query'], name='store_produ_search__622b28_idx'),
        ),
    ]
