# Generated by Django 5.1.7 on 2025-04-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cartitem_created_at_cartitem_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductView',
        ),
    ]
