# Generated by Django 5.1.7 on 2025-04-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productembedding',
            name='product',
        ),
        migrations.DeleteModel(
            name='RecommendationModel',
        ),
        migrations.RemoveField(
            model_name='userembedding',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductEmbedding',
        ),
        migrations.DeleteModel(
            name='UserEmbedding',
        ),
    ]
